const generateDummyAttendee = (index, name, skill) => {
  const now = new Date().toISOString();
  return {
    id: `dummy-${index}`,
    sessionId: 'dummy-session',
    status: 'yes',
    createdAt: now,
    updatedAt: now,
    user: {
      id: `dummy-user-${index}`,
      name: name,
      email: `${name.toLowerCase().replace(/\s+/g, '')}@example.com`,
      phone: `555-${String(1000 + index).padStart(4, '0')}`,
      skill: skill,
      supabaseUserId: `dummy-supabase-${index}`,
      password: null,
      createdAt: now,
      userId: `dummy-user-${index}`,
    },
  };
};

export const DUMMY_ATTENDEES = [
  // generateDummyAttendee(1, "Matt", 8),
  // generateDummyAttendee(2, "Sarah", 6),
  // generateDummyAttendee(3, "Chris", 9),
  // generateDummyAttendee(4, "Jordan", 5),
  // generateDummyAttendee(5, "Alex", 7),
  // generateDummyAttendee(6, "Taylor", 4),
  // generateDummyAttendee(7, "Morgan", 8),
  // generateDummyAttendee(8, "Riley", 6),
  // generateDummyAttendee(9, "Casey", 9),
  // generateDummyAttendee(10, "Jamie", 5),
  // generateDummyAttendee(11, "Avery", 7),
  // generateDummyAttendee(12, "Quinn", 3),
  // generateDummyAttendee(13, "Blake", 8),
  // generateDummyAttendee(14, "Dakota", 6),
  // generateDummyAttendee(15, "Sage", 10),
  // generateDummyAttendee(16, "River", 4),
  // generateDummyAttendee(17, "Phoenix", 7),
  // generateDummyAttendee(18, "Skyler", 5),
  // generateDummyAttendee(19, "Rowan", 8),
  // generateDummyAttendee(20, "Finley", 6),
  // generateDummyAttendee(21, "Hayden", 9),
  // generateDummyAttendee(22, "Emery", 4),
  // generateDummyAttendee(23, "Reese", 7),
  // generateDummyAttendee(24, "Drew", 6),
  // generateDummyAttendee(25, "Cameron", 8),
  // generateDummyAttendee(26, "Logan", 5),
  // generateDummyAttendee(27, "Parker", 9),
  // generateDummyAttendee(28, "Jordan", 3),
  // generateDummyAttendee(29, "Alexis", 7),
  // generateDummyAttendee(30, "Dakota", 6),
  // generateDummyAttendee(31, "Sam", 8),
  // generateDummyAttendee(32, "Charlie", 4),
  // generateDummyAttendee(33, "Max", 9),
  // generateDummyAttendee(34, "Noah", 5),
  // generateDummyAttendee(35, "Ethan", 7),
  // generateDummyAttendee(36, "Liam", 6),
  // generateDummyAttendee(37, "Olivia", 8),
  // generateDummyAttendee(38, "Emma", 4),
  // generateDummyAttendee(39, "Sophia", 9),
  // generateDummyAttendee(40, "Isabella", 5),
  // generateDummyAttendee(41, "Mia", 7),
  // generateDummyAttendee(42, "Amelia", 6),
  // generateDummyAttendee(43, "Harper", 8),
  // generateDummyAttendee(44, "Evelyn", 3),
];

export const DUMMY_USERS = [
  { id: 1, name: 'Peepee' },
  { id: 2, name: 'Sarah Johnson' },
  { id: 3, name: 'Michael Chen' },
  { id: 4, name: 'Emily Rodriguez' },
  { id: 5, name: 'David Kim' },
  { id: 6, name: 'Jessica Martinez' },
  { id: 7, name: 'Ryan Thompson' },
  { id: 8, name: 'Amanda Lee' },
  { id: 9, name: 'Chris Wilson' },
  { id: 10, name: 'Lisa Anderson' },
  { id: 11, name: 'James Brown' },
  { id: 12, name: 'Maria Garcia' },
  { id: 13, name: 'Robert Taylor' },
  { id: 14, name: 'Jennifer White' },
  { id: 15, name: 'Daniel Moore' },
  { id: 16, name: 'Nicole Davis' },
  { id: 17, name: 'Kevin Miller' },
  { id: 18, name: 'Rachel Adams' },
  { id: 19, name: 'Brandon Scott' },
  { id: 20, name: 'Megan Parker' },
  { id: 21, name: 'Tyler Brooks' },
  { id: 22, name: 'Olivia Bennett' },
  { id: 23, name: 'Nathan Reed' },
  { id: 24, name: 'Sophia Rivera' },
  { id: 25, name: 'Ethan Murphy' },
  { id: 26, name: 'Ava Hughes' },
  { id: 27, name: 'Zachary Cooper' },
  { id: 28, name: 'Hannah Foster' },
  { id: 29, name: 'Joshua Collins' },
  { id: 30, name: 'Chloe Peterson' },
  { id: 31, name: 'Matthew Phillips' },
  { id: 32, name: 'Isabella Ward' },
  { id: 33, name: 'Samuel Turner' },
  { id: 34, name: 'Victoria Morgan' },
  { id: 35, name: 'Benjamin Evans' },
  { id: 36, name: 'Ella Ramirez' },
  { id: 37, name: 'Jason Campbell' },
  { id: 38, name: 'Grace Sanders' },
  { id: 39, name: 'Dylan Mitchell' },
  { id: 40, name: 'Natalie Brooks' },
  { id: 41, name: 'Alex Murphy' },
  { id: 42, name: 'Lauren Price' },
  { id: 43, name: 'Cameron Simmons' },
  { id: 44, name: 'Abigail Cox' },
  { id: 45, name: 'Logan Bailey' },
  { id: 46, name: 'Morgan Hughes' },
  { id: 47, name: 'Jake Ramirez' },
  { id: 48, name: 'Elena Flores' },
  { id: 49, name: 'Aaron Bennett' },
  { id: 50, name: 'Kayla Scott' },
  { id: 51, name: 'Trevor Phillips' },
  { id: 52, name: 'Zoe Campbell' },
  { id: 53, name: 'Connor Reyes' },
  { id: 54, name: 'Samantha Ward' },
  { id: 55, name: 'Ian Jenkins' },
  { id: 56, name: 'Paige Armstrong' },
  { id: 57, name: 'Kyle Martinez' },
  { id: 58, name: 'Madison Stone' },
  { id: 59, name: 'Hunter Fisher' },
  { id: 60, name: 'Lily Parker' },
  { id: 61, name: 'Eric Gomez' },
  { id: 62, name: 'Natalia Ruiz' },
  { id: 63, name: 'Chase Gardner' },
  { id: 64, name: 'Jasmine Elliott' },
  { id: 65, name: 'Colin Spencer' },
  { id: 66, name: 'Brooke Howard' },
  { id: 67, name: 'Tristan Wallace' },
  { id: 68, name: 'Maya Hernandez' },
  { id: 69, name: 'Christian Boyd' },
];
