const generateDummyAttendee = (index, name, skill, ogGroup = false) => {
  const now = new Date().toISOString();
  return {
    id: `dummy-${index}`,
    sessionId: 'dummy-session',
    status: 'yes',
    createdAt: now,
    updatedAt: now,
    user: {
      id: `dummy-user-${index}`,
      name: name,
      email: `${name.toLowerCase().replace(/\s+/g, '')}@example.com`,
      phone: `555-${String(1000 + index).padStart(4, '0')}`,
      skill: skill,
      ogGroup: ogGroup,
      supabaseUserId: `dummy-supabase-${index}`,
      password: null,
      createdAt: now,
      userId: `dummy-user-${index}`,
    },
  };
};

export const DUMMY_ATTENDEES = [
  generateDummyAttendee(1, "Alan Zhang", 8, true),
  generateDummyAttendee(2, "Andrew Zhang", 6, true),
  generateDummyAttendee(3, "Basel", 7, true),
  generateDummyAttendee(4, "Ben", 5),
  generateDummyAttendee(5, "BIN", 9, true),
  generateDummyAttendee(6, "Bing", 4),
  generateDummyAttendee(7, "Peng", 7, true),
  generateDummyAttendee(8, "Dan", 6, true),
  generateDummyAttendee(9, "David", 8),
  generateDummyAttendee(10, "Efrain Guzman", 5),
  generateDummyAttendee(11, "Evan Cresswell", 7, true),
  generateDummyAttendee(12, "Fila Perez", 6, true),
  generateDummyAttendee(13, "Frank Gallagher", 8, true),
  generateDummyAttendee(14, "Haewook Lee", 9, true),
  generateDummyAttendee(15, "Hao Jiang", 7, true),
  generateDummyAttendee(16, "Issac Zeng", 6, true),
  generateDummyAttendee(17, "Janine Blythe", 5, true),
  generateDummyAttendee(18, "Jason Moore", 8, true),
  generateDummyAttendee(19, "Jeremy Krug", 7, true),
  generateDummyAttendee(20, "Jesus Rosas", 4),
  generateDummyAttendee(21, "Joe (ZZ)", 9, true),
  generateDummyAttendee(22, "Joe Carley", 6, true),
  generateDummyAttendee(23, "Julio Vinciguerra", 7, true),
  generateDummyAttendee(24, "Jun Liu", 5),
  generateDummyAttendee(25, "Junjie Mei", 8, true),
  generateDummyAttendee(26, "Khal H", 6),
  generateDummyAttendee(27, "Liang Du", 7, true),
  generateDummyAttendee(28, "Sarah Johnson", 6),
  generateDummyAttendee(29, "Michael Chen", 7),
  generateDummyAttendee(30, "Emily Rodriguez", 5),
  generateDummyAttendee(31, "Ryan Thompson", 8),
  generateDummyAttendee(32, "Amanda Lee", 6),
  generateDummyAttendee(33, "Chris Wilson", 9),
  generateDummyAttendee(34, "Lisa Anderson", 4),
  generateDummyAttendee(35, "James Brown", 7),
  generateDummyAttendee(36, "Maria Garcia", 5),
  generateDummyAttendee(37, "Robert Taylor", 8),
  generateDummyAttendee(38, "Jennifer White", 6),
  generateDummyAttendee(39, "Daniel Moore", 7),
  generateDummyAttendee(40, "Nicole Davis", 5),
  generateDummyAttendee(41, "Kevin Miller", 9),
  generateDummyAttendee(42, "Rachel Adams", 6),
  generateDummyAttendee(43, "Brandon Scott", 7),
  generateDummyAttendee(44, "Megan Parker", 4),
  generateDummyAttendee(45, "Tyler Brooks", 8),
];

export const DUMMY_USERS = [
  { id: 2, name: 'Alan Zhang', ogGroup: true },
  { id: 3, name: 'Andrew Zhang', ogGroup: true },
  { id: 4, name: 'Basel', ogGroup: true },
  { id: 5, name: 'Ben' },
  { id: 6, name: 'BIN', ogGroup: true },
  { id: 7, name: 'Bing' },
  { id: 8, name: 'Peng', ogGroup: true },
  { id: 9, name: 'Dan', ogGroup: true },
  { id: 10, name: 'David' },
  { id: 11, name: 'Efrain Guzman' },
  { id: 12, name: 'Evan Cresswell', ogGroup: true },
  { id: 13, name: 'Fila Perez', ogGroup: true },
  { id: 14, name: 'Frank Gallagher', ogGroup: true },
  { id: 15, name: 'Haewook Lee', ogGroup: true},
  { id: 16, name: 'Hao Jiang', ogGroup: true },
  { id: 17, name: 'Issac Zeng', ogGroup: true },
  { id: 18, name: 'Janine Blythe', ogGroup: true },
  { id: 19, name: 'Jason Moore', ogGroup: true },
  { id: 20, name: 'Jeremy Krug', ogGroup: true },
  { id: 21, name: 'Jesus Rosas' },
  { id: 22, name: 'Joe (ZZ)', ogGroup: true },
  { id: 23, name: 'Joe Carley', ogGroup: true },
  { id: 24, name: 'Julio Vinciguerra', ogGroup: true },
  { id: 25, name: 'Jun Liu' },
  { id: 26, name: 'Junjie Mei', ogGroup: true },
  { id: 27, name: 'Khal H' },
  { id: 28, name: 'Liang Du', ogGroup: true },
  { id: 29, name: 'Sarah Johnson' },
  { id: 30, name: 'Michael Chen' },
  { id: 31, name: 'Emily Rodriguez' },
  { id: 32, name: 'Ryan Thompson' },
  { id: 33, name: 'Amanda Lee' },
  { id: 34, name: 'Chris Wilson' },
  { id: 35, name: 'Lisa Anderson' },
  { id: 36, name: 'James Brown' },
  { id: 37, name: 'Maria Garcia' },
  { id: 38, name: 'Robert Taylor' },
  { id: 39, name: 'Jennifer White' },
  { id: 40, name: 'Daniel Moore' },
  { id: 41, name: 'Nicole Davis' },
  { id: 42, name: 'Kevin Miller' },
  { id: 43, name: 'Rachel Adams' },
  { id: 44, name: 'Brandon Scott' },
  { id: 45, name: 'Megan Parker' },
  { id: 46, name: 'Tyler Brooks' },
  { id: 47, name: 'Olivia Bennett' },
  { id: 48, name: 'Nathan Reed' },
  { id: 49, name: 'Sophia Rivera' },
  { id: 50, name: 'Ethan Murphy' },
  { id: 51, name: 'Zachary Cooper' },
  { id: 52, name: 'Hannah Foster' },
  { id: 53, name: 'Joshua Collins' },
  { id: 54, name: 'Chloe Peterson' },
  { id: 55, name: 'Matthew Phillips' },
  { id: 56, name: 'Isabella Ward' },
  { id: 57, name: 'Samuel Turner' },
  { id: 58, name: 'Victoria Morgan' },
  { id: 59, name: 'Benjamin Evans' },
  { id: 60, name: 'Dylan Mitchell' },
  { id: 61, name: 'Grace Sanders' },
  { id: 62, name: 'Cameron Simmons' },
  { id: 63, name: 'Logan Bailey' },
  { id: 64, name: 'Elena Flores' },
  { id: 65, name: 'Aaron Bennett' },
  { id: 66, name: 'Connor Reyes' },
  { id: 67, name: 'Maya Hernandez' },
  { id: 68, name: 'Tristan Wallace' },
  { id: 69, name: 'Natalia Ruiz' },
];
