const generateDummyAttendee = (index, name, skill) => {
  const now = new Date().toISOString();
  return {
    id: `dummy-${index}`,
    sessionId: "dummy-session",
    status: "yes",
    createdAt: now,
    updatedAt: now,
    user: {
      id: `dummy-user-${index}`,
      name: name,
      email: `${name.toLowerCase().replace(/\s+/g, "")}@example.com`,
      phone: `555-${String(1000 + index).padStart(4, "0")}`,
      skill: skill,
      supabaseUserId: `dummy-supabase-${index}`,
      password: null,
      createdAt: now,
      userId: `dummy-user-${index}`,
    },
  };
};

export const DUMMY_ATTENDEES = [
  // generateDummyAttendee(1, "Matt", 8),
  // generateDummyAttendee(2, "Sarah", 6),
  // generateDummyAttendee(3, "Chris", 9),
  // generateDummyAttendee(4, "Jordan", 5),
  // generateDummyAttendee(5, "Alex", 7),
  // generateDummyAttendee(6, "Taylor", 4),
  // generateDummyAttendee(7, "Morgan", 8),
  // generateDummyAttendee(8, "Riley", 6),
  // generateDummyAttendee(9, "Casey", 9),
  // generateDummyAttendee(10, "Jamie", 5),
  // generateDummyAttendee(11, "Avery", 7),
  // generateDummyAttendee(12, "Quinn", 3),
  // generateDummyAttendee(13, "Blake", 8),
  // generateDummyAttendee(14, "Dakota", 6),
  // generateDummyAttendee(15, "Sage", 10),
  // generateDummyAttendee(16, "River", 4),
  // generateDummyAttendee(17, "Phoenix", 7),
  // generateDummyAttendee(18, "Skyler", 5),
  // generateDummyAttendee(19, "Rowan", 8),
  // generateDummyAttendee(20, "Finley", 6),
  // generateDummyAttendee(21, "Hayden", 9),
  // generateDummyAttendee(22, "Emery", 4),
  // generateDummyAttendee(23, "Reese", 7),
  // generateDummyAttendee(24, "Drew", 6),
  // generateDummyAttendee(25, "Cameron", 8),
  // generateDummyAttendee(26, "Logan", 5),
  // generateDummyAttendee(27, "Parker", 9),
  // generateDummyAttendee(28, "Jordan", 3),
  // generateDummyAttendee(29, "Alexis", 7),
  // generateDummyAttendee(30, "Dakota", 6),
  // generateDummyAttendee(31, "Sam", 8),
  // generateDummyAttendee(32, "Charlie", 4),
  // generateDummyAttendee(33, "Max", 9),
  // generateDummyAttendee(34, "Noah", 5),
  // generateDummyAttendee(35, "Ethan", 7),
  // generateDummyAttendee(36, "Liam", 6),
  // generateDummyAttendee(37, "Olivia", 8),
  // generateDummyAttendee(38, "Emma", 4),
  // generateDummyAttendee(39, "Sophia", 9),
  // generateDummyAttendee(40, "Isabella", 5),
  // generateDummyAttendee(41, "Mia", 7),
  // generateDummyAttendee(42, "Amelia", 6),
  // generateDummyAttendee(43, "Harper", 8),
  // generateDummyAttendee(44, "Evelyn", 3),
];
